#!/usr/bin/env bash
# 1-install_nginx_web_server

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx restart
