#!/usr/bin/env bash
# a script bash that display currently running processes
terminate() {
       echo "I hate the kill command"
       rm /var/run/myscript.pid
       exit 0
}

interrupt() {
	echo "Y U no love me?!"
	exit 0
}

trap terminate SIGTERM SIGQUIT
trap interrupt SIGINT

while true; do
	echo "To infinity and beyond"
	sleep 2
done

